### ISSUE TITLE
NullReferenceException at MumbleSharp.Audio.Codecs.Opus.OpusDecoder..ctor

### ISSUE THREAD

**Issue by smarper** [martindevans/MumbleSharp#69]
I loaded the console Application for MumbleSharp (latest version) in VS2017, .NET 4.7.2 and could compile everything. But I always get following error:
   at MumbleSharp.Audio.Codecs.Opus.OpusDecoder..ctor(Int32 outputSampleRate, Int32 outputChannelCount)
   at MumbleSharp.Audio.Codecs.Opus.OpusCodec..ctor(Int32 sampleRate, Byte sampleBits, Byte channels, UInt16 frameSize)
   at MumbleSharp.Audio.CodecSet.<>c__DisplayClass4_0.<.ctor>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at MumbleSharp.Audio.AudioEncodingBuffer.Encode(SpeechCodecs codec)
   at MumbleSharp.BasicMumbleProtocol.EncodingThreadEntry(Exception& exception)
   
The opus.dll files are in the output directory. I don´t know what I´m doing wrong here. Has someone any ideas? Thanks!

**Comment by smarper** [comment]
Here are the errors:
BasicMumbleProtocol's _encodingThread was terminated unexpectedly because of a System.NullReferenceException

   at MumbleSharp.BasicMumbleProtocol.<Initialise>b__40_1()
   at System.Threading.ThreadStart.Invoke()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Do you need other Infos? Unfortunately, I can´t compile MumbleSharp directly at the moment and check what´s null. Seems to be the Opus Codec. Because something like 
OpusCodec opusCodec = new OpusCodec();
leads to the same exception.

![Screenshot 2023-04-24 174408](https://user-images.githubusercontent.com/43525291/234048017-ac6618c8-97fa-44de-9c8c-dc778b9ca101.png)

**Comment by smarper** [comment]
Problem was, that opus.dll was not in the output Subfolder "\Audio\Codecs\Opus\Libs\32bit"
